DEBUG = False
# Sentry needs TEMPLATE_DEBUG set to true
TEMPLATE_DEBUG = True


AGGREGATES_API_BASE_URL = "http://example.com/api/1.0/"
LOBBYING_API_BASE_URL = "http://example.com/api/1.0/"
API_KEY = "asdf"
SUNLIGHT_API_KEY = "your key here"

EMAIL_HOST = ""
EMAIL_PORT = ""
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
EMAIL_USE_TLS = True
EMAIL_RECIPIENTS = ('',)

AWS_ACCESS_KEY_ID = ''
AWS_SECRET_ACCESS_KEY = ''
AWS_STORAGE_BUCKET_NAME = ''
AWS_S3_CUSTOM_DOMAIN = ''
